import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Next.js 16 Example",
  description: "Basic routing example with App Router",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body>
        <header style={{ padding: "20px", background: "#f5f5f5" }}>
          <nav style={{ display: "flex", gap: "15px" }}>
            <Link href="/">Home</Link>
            <Link href="/dashboard">DashBoard</Link>
            <Link href="/contact">Contact</Link>
          </nav>
        </header>

        <main style={{ padding: "40px" }}>{children}</main>

        <footer style={{ textAlign: "center", padding: "20px", background: "#f5f5f5" }}>
          <p>© 2025 My Next.js App</p>
        </footer>
      </body>
    </html>
  );
}


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="ko">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
